# Utiliser l'image de base Miniconda pour un environnement léger avec Conda
FROM continuumio/miniconda3:4.8.2

# Installer MLflow et boto3
RUN pip install mlflow boto3

# Définir le répertoire de travail
WORKDIR /mlflow

# Démarrer le serveur MLflow avec les arguments appropriés
CMD ["mlflow", "server", "--backend-store-uri", "sqlite:///mlflow.db", "--default-artifact-root", "s3://final-project-jedha-team-anne/resultats/", "--host", "0.0.0.0", "-p", "5000"]
